name: Publish NuGet Package

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.x'
  PACKAGE_NAME: 'Bank' # Nombre del paquete
  PACKAGE_VERSION: '1.0.0' # Puedes actualizarlo dinámicamente si prefieres
  GITHUB_REPOSITORY: 'OWNER/REPO' # Reemplaza con tu usuario y repo

jobs:
  build-and-publish:
    name: Build & Publish NuGet Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack Bank/Bank.Domain/Bank.Domain.csproj --configuration Release --output .

      - name: Publish package to GitHub Packages
        run: dotnet nuget push *.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.SONAR_TOKEN }} --skip-duplicate
