name: Create GitHub Release

on:
  push:
    tags:
      - "v*.*.*" # Detecta versiones como v1.0.0, v1.1.0, etc.
  workflow_dispatch:

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate release notes
        id: release_notes
        run: |
          echo "## Changelog" > RELEASE_NOTES.md
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s" >> RELEASE_NOTES.md

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body_path: "RELEASE_NOTES.md"
          token: ${{ secrets.SONAR_TOKEN }}
